export {
  DUMMY_WORKTIME_EDIT_REQUEST,
  DUMMY_WORKTIME_COMPLETE_EDIT_REQUEST,
  DUMMY_WORKTIME_QUICK_SEARCH_RESULT,
  DUMMY_WORKTIME_DETAIL_SCHEDULE,
  DUMMY_WORKTIME_DETAIL_SEARCH_TO_ADD,
} from "./dummy";
