export {
  DUMMY_GET_SCHEDULE,
  DUMMY_NEXT_MONTH_SCHEDULE,
  DUUMY_SCHEDULE_CHANGE_HISTORY,
} from "./dummy";

export {
  SLOTS_PER_DAY,
  SLOT_STATUS_CLASS_NAME,
  SLOT_REQUEST_EDIT_CLASS_NAME,
} from "./slot";
