export const DUMMY_MEMBER_LIST = [
  {
    userId: 1,
    name: "홍길동",
    studentNumber: 202011234,
    department: "컴퓨터공학과",
    grade: 3,
    phone: "010-1234-5678",
    weeklyWorkedHours: 4,
    monthlyWorkedHours: 15,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 2,
    name: "김민준",
    studentNumber: 202111235,
    department: "컴퓨터공학과",
    grade: 4,
    phone: "010-2345-6789",
    weeklyWorkedHours: 8,
    monthlyWorkedHours: 32,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 3,
    name: "이서연",
    studentNumber: 202211236,
    department: "소프트웨어학과",
    grade: 3,
    phone: "010-3456-7890",
    weeklyWorkedHours: 12,
    monthlyWorkedHours: 48,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 4,
    name: "박지훈",
    studentNumber: 202311237,
    department: "전자공학과",
    grade: 2,
    phone: "010-4567-8901",
    weeklyWorkedHours: 6,
    monthlyWorkedHours: 24,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 5,
    name: "최유진",
    studentNumber: 202411238,
    department: "산업공학과",
    grade: 1,
    phone: "010-5678-9012",
    weeklyWorkedHours: 10,
    monthlyWorkedHours: 40,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 6,
    name: "정현우",
    studentNumber: 202011239,
    department: "컴퓨터공학과",
    grade: 4,
    phone: "010-6789-0123",
    weeklyWorkedHours: 5,
    monthlyWorkedHours: 20,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 7,
    name: "강수빈",
    studentNumber: 202111240,
    department: "소프트웨어학과",
    grade: 3,
    phone: "010-7890-1234",
    weeklyWorkedHours: 7,
    monthlyWorkedHours: 28,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 8,
    name: "조민재",
    studentNumber: 202211241,
    department: "전자공학과",
    grade: 3,
    phone: "010-8901-2345",
    weeklyWorkedHours: 9,
    monthlyWorkedHours: 36,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 9,
    name: "윤지아",
    studentNumber: 202311242,
    department: "산업공학과",
    grade: 2,
    phone: "010-9012-3456",
    weeklyWorkedHours: 11,
    monthlyWorkedHours: 44,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
  {
    userId: 10,
    name: "한도윤",
    studentNumber: 202411243,
    department: "컴퓨터공학과",
    grade: 1,
    phone: "010-0123-4567",
    weeklyWorkedHours: 4,
    monthlyWorkedHours: 16,
    editRequestCount: 9,
    monthlyEditRequestCount: 3,
    attendanceIssueCount: 6,
    monthlyAttendanceIssueCount: 4,
  },
];

export const DUMMY_MEMBER_DETAIL_INFO = {
  userId: 1,
  name: "홍길동",
  studentNumber: "202012345",
  department: "컴퓨터공학과",
  grade: 3,
  phoneNumber: "010-1234-5678",
  commuteStartDate: "2026.03.01",
  weeklyWorkedHours: 4,
  monthlyWorkedHours: 15,
  editRequestCount: 9,
  confirmedRequestCount: 4,
  accountId: "wori1206",
  lastAccessDate: "2026. 03. 04. 15:30",
};
